### ISSUE TITLE
Use dlopen() for OpenSSL

### ISSUE THREAD

**Issue by probonopd** [probonopd/zsync-curl#21] opened 2017-05-28 08:11 UTC
We should use Use `dlopen()` for OpenSSL as described in
http://www.bruijntjes.net/blog/post/8c504e2f4a79ff837221d77183c88d00. Currently the semistatic build fails on openSUSE due to a slight mismatch in the expected OpenSSL version.

**Comment by TheAssassin** [comment] 2017-06-15 18:13
The problem is that OpenSSL is not a dependency of our code, it would be loaded by cURL, depending on how cURL has been compiled. E.g., when using another crypto library such as mbedTLS, OpenSSL wouldn't even be used.

As this can't be done in our codebase, I'm going to close this issue. Instead, I'd recommend bundling our own crypto library. We can turn off most features, as we can predict pretty well what parts we need. These few additional kbytes won't turn out to be really problematic in my opinion. In fact, a vanilla mbedTLS build just adds ~500 kB, which is really acceptable, considering that it can be optimized by adjusting the configure flags.

**Closed as completed by TheAssassin** 2017-06-15 18:13 UTC
Labels: enhancement

**Comment by probonopd** [comment] 2017-06-16 05:36
Would that mean that we also need to maintain our own set of certificates? I was really looking for a way (for this and other AppImages) to use "whatever OpenSSL the distributions happens to ship", because a) they seemingly cannot agree on what and how to ship and b) newer OpenSSL libraries seem not to run applications compiled against older versions well, especially if the versions differ in letters (which is, in my view, a bug).

So yes, we would need to change the _libcurl_ code to dlopen() whatever OpenSSL version is there. Maybe we should even ask the upstream curl project to consider doing this?

**Comment by TheAssassin** [comment] 2017-06-16 08:50
No, we don't have to ship our own certificate chain. As long as a package like `ca-certificates` for Debian/Ubuntu is installed, and I guess the OpenSSL package we expect to be there depends on that, we're good to go.
